lib/postmodern_web/router.ex
defmodule PostmodernWeb.Router do
  use PostmodernWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Postmodern.Auth.Pipeline
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Postmodern.CurrentUser
end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", PostmodernWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController do
        resources "/profiles", ProfileController
    end

    get "/sign_up", UserController, :new
    get "/sign_in", SessionController, :index
    post "/sign_in", SessionController, :login
    post "/sign_out", SessionController, :logout
    resources "/articles", ArticleController
  end

  # Definitely logged in scope
  scope "/", PostmodernWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    resources "/dashboard", DashboardController
    get "/dashboard", DashboardController, :index
    get "/dashboard/articles", ArticleController, :index
    get "/secret", SessionController, :secret
  end

  # Other scopes may use custom stacks.
  # scope "/api", PostmodernWeb do
  #   pipe_through :api
  # end
end

lib/postmodern_web/views/shared_view.ex
defmodule PostmodernWeb.SharedView do
  use PostmodernWeb, :view
end

lib/postmodern_web/templates/shared/_navbar.html.eex
<header class="header">
  <nav role="navbar navbar-inverse bg-inverse navbar-fixed-top">

<span class="brand">
  <%= link "postModern", to: dashboard_path(@conn, :index), class: "h3" %>
</span>

    <div class="dropdown float-right">
    <button class="btn btn-dropdown dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

    <%#   <%= if @current_user == !nil do %>
    <%#     <%= @current_user.display_name %>
    <%#       <% else %>

      <%= unless Guardian.Plug.authenticated?(@conn, []) do %>
           User Menu
      <% else %>
          Logged In
      <% end %>
    <%#       <% end %>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuButton">
      <%= if Guardian.Plug.authenticated?(@conn, []) do %>

      <li class="dropdown"><%= link "New Article", to: article_path(@conn, :new), class: "dropdown-item" %></li>
      <li class="dropdown"><%= link "User Profiles", to: user_path(@conn, :index), class: "dropdown-item" %></li>
      <li class="divider"></li>
      <li class="dropdown"><%= link "Logout", to: session_path(@conn, :logout), method:
      :post,  class: "dropdown-item"  %></li>
      <% else %>

    <li class="dropdown"><%= link "Sign In", to: session_path(@conn, :index), class: "dropdown-item"  %></li>
      <li class="dropdown"><%= link "Sign Up", to: user_path(@conn, :new), class: "dropdown-item"  %></li>
      <% end %>
    </ul>
  </div>


  </nav>
</header>

lib/postmodern_web/templates/shared/_sidebar.html.eex
<div id="sidebar" class="sidebar col-md-2">
  <nav role="navbar navbar-fixed-top">
    <div id="search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="@Search" aria-describedby="sizing-addon2 place">
      </div>
    </div>
  </nav>
    <p>Articles will eventually appear here</p>
    <%= render PostmodernWeb.ArticleView, "_stream.html", conn: @conn %>

</div>